In [4]:
# We start by importing pandas and the required functions
import pandas as pd
import numpy as np
# Then we import the designated file
df=pd.read_csv("C:/Users/danca/Downloads/Yellow_Taxi_Trip_Data.csv")

In [55]:
# Preview data
df.head()

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
1,35634249,1,04/11/2017 2:53:28 PM,04/11/2017 3:19:58 PM,1,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
2,106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75
3,38942136,2,05/07/2017 1:17:59 PM,05/07/2017 1:48:14 PM,1,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69
4,30841670,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,1,4.37,1,N,4,112,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80

In [11]:
#We do an inital check
#Information ,missing values & basic statistics
df.info()
df.isnull()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22699 entries, 0 to 22698
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             22699 non-null  int64
 1   VendorID               22699 non-null  int64
 2   tpep_pickup_datetime   22699 non-null  object
 3   tpep_dropoff_datetime  22699 non-null  object
 4   passenger_count        22699 non-null  int64
 5   trip_distance          22699 non-null  float64
 6   RatecodeID             22699 non-null  int64
 7   store_and_fwd_flag     22699 non-null  object
 8   PULocationID           22699 non-null  int64
 9   DOLocationID           22699 non-null  int64
 10  payment_type           22699 non-null  int64
 11  fare_amount            22699 non-null  float64
 12  extra                  22699 non-null  float64
 13  mta_tax                22699 non-null  float64
 14  tip_amount             22699 non-null  float64
 15  tolls_amount           22699 non-null  float64
 16  improvement_surcharge  22699 non-null  float64
 17  total_amount           22699 non-null  float64
dtypes: float64(8), int64(7), object(3)
memory usage: 3.1+ MB

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22694,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22695,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22696,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22697,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22698,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
#Now we standardize some formats to be easily used in coding
df['tpep_dropoff_datetime']=pd.to_datetime(df['tpep_dropoff_datetime'])
df['tpep_pickup_datetime']=pd.to_datetime(df['tpep_pickup_datetime'])

In [19]:
df.head()

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,24870114,2,2017-03-25 08:55:43,2017-03-25 09:09:47,6,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
1,35634249,1,2017-04-11 14:53:28,2017-04-11 15:19:58,1,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
2,106203690,1,2017-12-15 07:26:56,2017-12-15 07:34:08,1,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75
3,38942136,2,2017-05-07 13:17:59,2017-05-07 13:48:14,1,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69
4,30841670,2,2017-04-15 23:32:20,2017-04-15 23:49:03,1,4.37,1,N,4,112,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80

In [29]:
#We select crucial variables that will require a more in-depth analysis.
#These variables will become the core variables for regression analysis when determining fare amount.
numerical_cols=['trip_distance','fare_amount','total_amount','tolls_amount','extra','tip_amount','passenger_count']
desc_stats=df[numerical_cols].aggregate(['mean','std','min','max'])
desc_stats
#Mean
#Useful for a simple starting prediction
#Standard Deviation (volatility)
#High std → harder to predict accurately
#Low std → easier, more stable pricing
#Min & Max (Important for Boundaries)
#Helps define realistic prediction limits

,trip_distance,fare_amount,total_amount,tolls_amount,extra,tip_amount,passenger_count
mean,2.913313,13.026629,16.310502,0.312542,0.333275,1.835781,1.642319
std,3.653171,13.243791,16.097295,1.399212,0.463097,2.800626,1.285231
min,0.000000,-120.000000,-120.300000,0.000000,-1.000000,0.000000,0.000000
max,33.960000,999.990000,1200.290000,19.100000,4.500000,200.000000,6.000000

In [5]:
#Now, next are variables that don't need descriptive analysis but are still important
#Number of payments per method
payment_counts=df['payment_type'].value_counts()
print(payment_counts)
#frequency per Vendor sold
vendor_sales=df['VendorID'].value_counts()
print(vendor_sales)

payment_type
1    15265
2     7267
3      121
4       46
Name: count, dtype: int64
VendorID
2    12626
1    10073
Name: count, dtype: int64

In [7]:
#Next, we categorise variables in certain scenarios.
#Average Amount of tips per method of payment
df.groupby('payment_type')['tip_amount'].mean()

payment_type
1    2.7298
2    0.0000
3    0.0000
4    0.0000
Name: tip_amount, dtype: float64

In [9]:
#Average number of tips per passenger carried
df.groupby('passenger_count')['tip_amount'].mean()

passenger_count
0    2.135758
1    1.848920
2    1.856378
3    1.716768
4    1.530264
5    1.873185
6    1.720260
Name: tip_amount, dtype: float64

In [68]:
#Amount collected per method of payment
df.groupby('payment_type')['total_amount'].sum()

payment_type
1    269634.51
2     98437.48
3      1643.14
4       516.96
Name: total_amount, dtype: float64

In [70]:
#Total amount collected by each vendor
df.groupby('VendorID')['total_amount'].sum()

VendorID
1    164170.95
2    206061.14
Name: total_amount, dtype: float64

In [71]:
#Amount earned per number of passengers
df.groupby('passenger_count')['total_amount'].sum()

passenger_count
0       581.60
1    259012.88
2     57475.47
3     15835.85
4      7586.50
5     18589.89
6     11149.90
Name: total_amount, dtype: float64

In [8]:
#Average total amount per each vendor
df.groupby('VendorID')['total_amount'].mean()

VendorID
1    16.298119
2    16.320382
Name: total_amount, dtype: float64

In [17]:
#Filter the data for credit card payment only
credit_card = df[df['payment_type']==1]
print(credit_card)

       Unnamed: 0  VendorID    tpep_pickup_datetime   tpep_dropoff_datetime  \
0        24870114         2   03/25/2017 8:55:43 AM   03/25/2017 9:09:47 AM
1        35634249         1   04/11/2017 2:53:28 PM   04/11/2017 3:19:58 PM
2       106203690         1   12/15/2017 7:26:56 AM   12/15/2017 7:34:08 AM
3        38942136         2   05/07/2017 1:17:59 PM   05/07/2017 1:48:14 PM
5        23345809         2   03/25/2017 8:34:11 PM   03/25/2017 8:42:11 PM
...           ...       ...                     ...                     ...
22692    60425673         1   07/16/2017 3:22:51 AM   07/16/2017 3:40:52 AM
22693    67858616         2  08/10/2017 10:20:04 PM  08/10/2017 10:29:31 PM
22695    66632549         2   08/06/2017 4:43:59 PM   08/06/2017 5:24:47 PM
22697    60217333         2  07/15/2017 12:56:30 PM   07/15/2017 1:08:26 PM
22698    17208911         1   03/02/2017 1:02:49 PM   03/02/2017 1:16:09 PM

       passenger_count  trip_distance  RatecodeID store_and_fwd_flag  \
0                    6           3.34           1                  N
1                    1           1.80           1                  N
2                    1           1.00           1                  N
3                    1           3.70           1                  N
5                    6           2.30           1                  N
...                ...            ...         ...                ...
22692                1           5.70           1                  N
22693                1           0.89           1                  N
22695                1          16.71           2                  N
22697                1           2.36           1                  N
22698                1           2.10           1                  N

       PULocationID  DOLocationID  payment_type  fare_amount  extra  mta_tax  \
0               100           231             1         13.0    0.0      0.5
1               186            43             1         16.0    0.0      0.5
2               262           236             1          6.5    0.0      0.5
3               188            97             1         20.5    0.0      0.5
5               161           236             1          9.0    0.5      0.5
...             ...           ...           ...          ...    ...      ...
22692           249            17             1         19.0    0.5      0.5
22693           229           170             1          7.5    0.5      0.5
22695           132           164             1         52.0    0.0      0.5
22697            68           144             1         10.5    0.0      0.5
22698           239           236             1         11.0    0.0      0.5

       tip_amount  tolls_amount  improvement_surcharge  total_amount
0            2.76          0.00                    0.3         16.56
1            4.00          0.00                    0.3         20.80
2            1.45          0.00                    0.3          8.75
3            6.39          0.00                    0.3         27.69
5            2.06          0.00                    0.3         12.36
...           ...           ...                    ...           ...
22692        4.05          0.00                    0.3         24.35
22693        1.76          0.00                    0.3         10.56
22695       14.64          5.76                    0.3         73.20
22697        1.70          0.00                    0.3         13.00
22698        2.35          0.00                    0.3         14.15

[15265 rows x 18 columns]